# Generated by Django 3.2.12 on 2022-03-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='like'),
        ),
    ]
